#docker-compose.yml 

services:
#Nosso serviço de banco de dados
  postgres:
    image: postgres:15-alpine
    container_name: catalogo_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: senha123
      POSTGRES_DB: catalogo_produtos
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/postgres_data

volumes:
  postgres_data: